#! /usr/bin/env python

import sys, argparse



# Grab command line arguments
parser = argparse.ArgumentParser(description='Script that uses a config file to generate a WordPress plugin scaffold.')
parser.add_argument('infile', nargs='?', type=argparse.FileType('r'), default=sys.stdin, help='an integer for the accumulator')
args = parser.parse_args()
